//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int ID_District { get; set; }
        public string NameDistrict { get; set; }
        public Nullable<int> House_id { get; set; }
    
        public virtual houses houses { get; set; }
    }
}
